yaml

title: Cassie
description: This is Cassie's personal site, created at 10-6,2026.
url: "https://purelycassie.github.io"
baseurl: ""
permalink: /:categories/:title/
markdown: kramdown

plugins:
	- jekyll-feed
	- jekyll-seo-tag
